version: '3'
services:
  itinovstrapi:
    container_name: itinovstrapi
    build:
      context: .
      dockerfile: Dockerfile.prod
    image: itinovstrapi:latest
    restart: unless-stopped
    env_file: .env
    volumes:
      - ./config:/opt/app/config
      - ./src:/opt/app/src
      - ./package.json:/opt/package.json
      - ./package-lock.json:/opt/package-lock.json

      - ./.env:/opt/app/.env
      # - itinov_strapi_uploads:/opt/app/public/uploads
    ports:
      - '13379:13379'
    networks:
      - itinov
    depends_on:
      - itinovstrapiDB

  itinovstrapiDB:
    container_name: itinovstrapiDB
    platform: linux/amd64 #for platform error on Apple M1 chips
    restart: unless-stopped
    env_file: .env
    image: postgres:14.5-alpine
    environment:
      POSTGRES_USER: ${DATABASE_USERNAME}
      POSTGRES_PASSWORD: ${DATABASE_PASSWORD}
      POSTGRES_DB: ${DATABASE_NAME}
    volumes:
      - ./data:/var/lib/postgresql/data/ # if you want to use a bind folder
    ports:
      - '54329:54329'
    networks:
      - itinov

networks:
  itinov:
    external: true

volumes:
  itinov_strapi_uploads:
    external: true
