services:
  interface:
    container_name: nextjs
    image: itinovnextjs:latest
    build:
      context: .
      dockerfile: Dockerfile.prod
    env_file:
      - .env.local
    ports:
      - 3009:3009
    networks:
      - nginxproxymanagernetwork

networks:
  nginxproxymanagernetwork:
    external: true