services:
  itinovnextjs:
    container_name: itinovnextjs
    image: itinovnextjs:latest
    build:
      context: .
      dockerfile: Dockerfile.prod
    env_file:
      - .env.local
    ports:
      - 3009:3000
    networks:
      - nginxproxymanagernetwork

networks:
  nginxproxymanagernetwork:
    external: true